controller_list:
  - name: fake_urdf_robot_test_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
initial:  # Define initial robot poses per group
  - group: urdf_robot_test
    pose: tall